# Generated by Django 4.2 on 2025-05-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_delete",
            field=models.BooleanField(default=False),
        ),
    ]
